engines:
  eslint:
    enabled: true
  csslint:
    enabled: true
  coffeelint:
    enabled: true
  bundler-audit:
    enabled: true
  rubocop:
    enabled: true
  phpcodesniffer:
    enabled: true
  watson:
    enabled: true
ratings: 
  paths:
  - "**"
exclude_paths:
- "*.png"
- "*.svg"
- "image/*"
- "client/api-docs/lib/**/*"
- "client/api-docs/css/**/*"
- "client/api-docs/images/**/*"
- "client/api-docs/*.js"
- "client/style/js/**/*"
- "client/style/font-awesome/**/*"
- "client/style/fonts/**/*"
- "client/style/css/**/*"
- "client/style/img/**/*"
- "client/style/less/**/*"
- "*jcarousel*"
- "*jquery*"
